# The name of the workflow
name: code-analytics

# The event that triggers the workflow
on: [push]

jobs:
  flutter-install:
    name: install-flutter
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          architecture: x64
  pub-get:
    name: pub-get
    runs-on: ubuntu-latest
    needs: flutter-install
    steps: 
      - name: Run test
        run: flutter pub get
  code-analysis:
    name: analyze
    runs-on: ubuntu-latest
    needs: flutter-install
    steps:
      - uses: actions/checkout@v3
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Run test
        run: dart analyze .
  security-scan:
    name: security-scan
    runs-on: ubuntu-latest
    needs: flutter-install
    steps:
      - uses: actions/checkout@v3
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif