# The name of the workflow
name: unit-tests

# The event that triggers the workflow
on: [push]

jobs:
  code-analysis:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          architecture: x64
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Run test
        run: dart analyze .
  security-scan:
    name: widget-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'
      - name: Upload mobsfscan report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif