# The name of the workflow
name: first-test

# The event that triggers the workflow
on: [push]

jobs:
  dart-analyze:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'
        channel: 'stable'
        architecture: x64
    - name: Analyze code
      run: dart analyze .